Plugin-Encode: GB2312 #插件编码-编码
Plugin-Decode: GB18030 #插件编码-解码
Lang: #语言信息
  lang-EncodeSet: ""
  lang-ShowVersion: "&aRevivedLocyItem-{version} 插件已经在您的服务器上加载了."
  lang-illegal: "物品{item}在{where}处写错了!"